site_name: Temidayo
nav:
   - Home : aboutme.md
   - Tutorials: 
      - Django Tutorial: tutorial/django_tutorial.md
   - Opinion Posts:
      - Why Technical Writers Should be called Technical Marketers: opinion_posts/technical_marketers.md



extra_css:
    - css/extra.css
theme:
    name: readthedocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django
      
markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
    - md_in_html
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs
