site_name: Temidayo Azeez
nav:
   - Home : aboutme.md
   - How-To:
      - Search Query with Q Objects: howto/search_django.md
   - Tutorials: 
      - Django Tutorial: tutorial/django_tutorial.md
      - On Writing Tutorials: tutorial/about-tutorial.md
      - MindsDB Tutorial: tutorial/mindsdb_tutorial.md
      - MindsDB in Java: tutorial/java_mindsdb.md
   - Reference Guides:
      - On Writing Reference Guides: reference/about_reference.md
   - Opinion Posts:
      - Why Technical Writers Should be called Technical Marketers: opinion_posts/technical_marketers.md
   - Thought Leadership:
      - Techical Writing vs Marketing Writing: thought-leadership/technical_marketing.md 
   - Web Design Projects:
      - Bandwidth Hero Website: websites/bandwidthhero.md
      - Workstreamr Course Page: websites/workstreamr.md 



extra_css:
    - css/extra.css
theme:
    name: readthedocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django
      
markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
    - md_in_html
    # - mdx_gh_links:
    #     user: mkdocs
    #     repo: mkdocs
